import path from 'node:path';
import { fileURLToPath } from 'node:url';

const SOURCE_ROOT = path.dirname(fileURLToPath(import.meta.url));

/** Generate a project-scoped Codex MCP configuration without mutating the project. */
export function codexMcpConfig({ repo, agentId, serverPath = path.join(SOURCE_ROOT, 'mcp-server.mjs') }) {
  if (!repo) throw new Error('repo is required');
  if (!agentId?.trim()) throw new Error('agentId is required');
  const workspace = path.resolve(repo);
  const quoted = (value) => JSON.stringify(value);
  return [
    '# AgentGit: local-first collaboration tools for this workspace.',
    '# Generated by `agentgit codex-config`; paste into .codex/config.toml.',
    '[mcp_servers.agentgit]',
    'command = "node"',
    `args = [${[serverPath, '--repo', workspace, '--agent', agentId].map(quoted).join(', ')}]`,
    `cwd = ${quoted(workspace)}`,
    'default_tools_approval_mode = "writes"',
    '',
  ].join('\n');
}
